### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by talbaumel** [JafferWilson/Process-Data-of-CNN-DailyMail#1]
Hi, I'm trying to use your files to train [get-to-the-point](https://github.com/abisee/pointer-generator) on python3

When reading the vocab file I'm getting `UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 60: ordinal not in range(128)`

What encoding did you use?

Thanks!!! Tal

**Comment by talbaumel** [comment]
Full error:

```
Traceback (most recent call last):
  File "run_summarization.py", line 285, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run_summarization.py", line 242, in main
    vocab = Vocab(FLAGS.vocab_path, FLAGS.vocab_size) # create a vocabulary
  File "/gttp/pointer-generator-master/data.py", line 61, in __init__
    print('Warning: incorrectly formatted line in vocabulary file: %s\n' % line)
UnicodeEncodeError: 'ascii' codec can't encode character '\xa0' in position 60: ordinal not in range(128)
```

**Comment by talbaumel** [comment]
After settings `errors='ignore'` in the open command I'm getting:

```
Traceback (most recent call last):
  File "run_summarization.py", line 285, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run_summarization.py", line 242, in main
    vocab = Vocab(FLAGS.vocab_path, FLAGS.vocab_size) # create a vocabulary
  File "/gttp/pointer-generator-master/data.py", line 67, in __init__
    raise Exception('Duplicated word in vocabulary file: %s' % w)
Exception: Duplicated word in vocabulary file: fiance
```

**Comment by JafferWilson** [comment]
@talbaumel I haven't used any of the encoding as such. This must be an issue with the Python version. I used Python 2.7.13 as the `make_datafiles.py` from the https://github.com/abisee/cnn-dailymail was compatible with the Python2. If still you are facing the issue try to encode with `UTF-8`. Even I feel that you should try to input path as raw. Say `r"path-of-the-file"`. This might help. This encoding issue is a common issue between Python 2 and Python3.

**Comment by talbaumel** [comment]
Yes, it worked when switched 2.7

**Comment by JafferWilson** [comment]
Glad to hear.... :)
