### ISSUE TITLE
cPickle.UnpicklingError: invalid load key, '?'.

### ISSUE THREAD

**Issue by nyxjemk** [JafferWilson/Process-Data-of-CNN-DailyMail#2]
Unfortunately I'm not able to open the finished_files:

```
>>> import cPickle
>>> import cPickle as pickle
>>> pickle.load(open('train.bin', 'rb'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cPickle.UnpicklingError: invalid load key, '?'.
```

I tried different systems and python versions - no success.

Any idea what I can do?

**Comment by JafferWilson** [comment]
@nyxjemk Please let me know whether this issue is still there or not? How you resolved if the issue is resolved?

**Comment by nyxjemk** [comment]
I was following this repository:
https://github.com/hashbangCoder/Text-Summarization

But then when trying to open it, I got this error posted above. Later then I realized that different approaches are used. While [Text-Summarization](https://github.com/hashbangCoder/Text-Summarization) uses just cPickle for saving in its preprocessing the script provided in:
https://github.com/abisee/cnn-dailymail (I guess this is what you used)
Uses [strucs](https://docs.python.org/2/library/struct.html) which are written then directly to the file without pickling.

So this is not really related to the files provided by you, just a bit misleading that on [Text-Summarization](https://github.com/hashbangCoder/Text-Summarization) to suggest using the finished files.

Sorry I didn't realize this earlier.

**Comment by JafferWilson** [comment]
Great.. you realize.. thank you for sharing.
