### ISSUE TITLE
.bin files contain weird text

### ISSUE THREAD

**Issue by skydiving94** [JafferWilson/Process-Data-of-CNN-DailyMail#3]
Hi, I downloaded the finished version of the data and after I decompressed the file, and open test.bin or train.bin, I saw that a lot of weird letters/symbols. Now I am wondering if it was because I did something wrong...
![image](https://user-images.githubusercontent.com/7350056/59128708-753edb80-8930-11e9-9ca4-d194125f45ce.png)

**Comment by skydiving94** [comment]
I just realized that it is examples for tensorflow specifically.. Maybe I would have to process it differently so that it can work with pytorch...

**Comment by bnaman50** [comment]
Hey @timoderbeste, did you figure out a way to use these binary files for PyTorch? I am also looking for the same thing. 

Thanks, 
Naman
