### ISSUE TITLE
splitting train/test/dev separately for CNN and DailyMail

### ISSUE THREAD

**Issue by 85405115** [JafferWilson/Process-Data-of-CNN-DailyMail#5]
Does "Finished Files" have split CNN+DailyMail (together) to train/test/dev?

Is it possible that prepare train/test/dev partitions for CNN and DailyMail datasets separately?

Thanks.

**Comment by JafferWilson** [comment]
I guess you need to test it my friend. I have left using the summarization. I have created this for the people as they were not able to create the train/ test sets. 
If you have any other difficulty then let me know. But you have to try it.
Even you can download and check for the finished files.

**Comment by JafferWilson** [comment]
Need to close since there is no response.
